apiVersion: v1
kind: Service
metadata:
  name: microservices-service
spec:
  selector:
    app: microservices-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
